### ISSUE TITLE
Office equipment

### ISSUE THREAD

**Issue by stineb** [geco-bern/.github#2]
First priority to get from uni stores. Contacted Adrian Thomet to be shown what's available. Viewing TBD. 
Second priority place order.

## 414 (Beni)

- 1 stand-up desk
- 1 small conference table, round
- 1 office chair
- 1 Wandgestell
- 1 desk lamp
- 1 office small table
- 1 mobile TV stand
- 1 whiteboard

## 413 (Pascal, Laura, Jaideep, Postdoc from 2023)

- 4 office chairs
- 2 stand-up desks
- 1 white board
- 2 office desks (from Beni office)
- 4 drawer furnitures
- 4 desktop lamps

## 407 (Koen, Pepa)

- 2 office chairs
- 1 white board
- 2 stand-up desks
- 2 desktop lamps
- 2 drawer furnitures

## 408 pool (Yunke, Francesco, Didem, Selene, Jiarui, Yunpeng)

(nothing at this point)

## Common

- 3 fans

## Office "consumables"

pens / rulers / paper etc. can be obtained in the printer room on 2nd floor (backside, next to toilets)

**Comment by stineb** [comment]
To keep the overview, could we start a table that contains 

- item
- status (planned, ordered, obtained, allocated to person)

@khufkens

**Comment by khufkens** [comment]
Lab infrastructure listed here:
https://github.com/computationales/lab_infrastructure

Provisional, can be restructured later to a different project etc.

**Comment by pepaaran** [comment]
This is the website with fairly priced swiss standing desks:
https://www.xantron.ch/Stehtisch-hoehenverstellbar
