### ISSUE TITLE
Define access and profiles

### ISSUE THREAD

**Issue by stineb** [geco-bern/.github#3]
We should define access and equipment rights for different typical profiles of group members. For example:

- A: "core" postdoc and PhD, contract through Unibe
- B: external postdoc and PhD
- C: Unibe Master students
- D: External Master students

For each profile we need to define specific access rights for the following (to be informed what exactly):

- Unibe campus account
- obtain GECO laptop
- ...

### Action items

- [ ] Set up meeting with Isabella Geissbühler, Saliba, and Stefan Wunderle (tbc). Doodle for Week starting 22 Aug. @khufkens

**Comment by khufkens** [comment]
I assume you are talking about HPC computers here. Granular access control on a by person or group basis is a waste of time for our local setup. If people want to do harm, they will. People have physical access to systems which makes all the above fairly mute (they can just wipe the whole lot if they should want to).

**Comment by stineb** [comment]
Sure. We'll just need to define this. Let's arrange a meeting. Could you? thx

**Comment by stineb** [comment]
Suggestion for profiles. Suggested to be added to `system_administration` repo, see [here](https://github.com/computationales/system_administration/pull/2).

# Profiles
## A

PhD and postdocs who have a contract at Unibe.

- Unibe account
- Office key
- Network access
- Lab laptop
- Allocated office space

## B

Unibe Master students

- Unibe account
- Office key?
- Network access
- Allocated office space

## C

External and guest PhD and postdocs

- Unibe account
- Office key
- No network access?
- Allocated office space

### Ca

"Transition victims" special case, PhDs now registered at ETH with access to Euler

- No network access?
- Office space in pool room

## D

External Master students

- Office space in pool room
- No network access, use eduroam
